version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    volumes:
        - './backend:/app'
        - '/app/node_modules'
    ports:
        - 9000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true    
    depends_on:
        - db
    env_file: ./backend/.env
    environment:
        - MONGO_HOSTNAME=db
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

